name: Archive Repository and Share on Slack

on:
  push:
    branches:
      - main

jobs:
  archive-and-share:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create dist directory
        run: mkdir dist
      - name: Create archive
        run: tar -czf dist/repo-archive.tar.gz *
      - name: Share archive on Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dev-pull-request
          SLACK_COLOR: "good"
          SLACK_USERNAME: ${{ github.event.pull_request.user.login }}
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_MESSAGE: "New Figma plugin Update available here: ${{ github.repository }} dist/repo-archive.tar.gz please download @Haider Ali Khan"
          SLACK_WEBHOOK: https://hooks.slack.com/services/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