name: Archive Repository and Share on Slack

on:
  push:
    branches:
      - main

jobs:
  archive-and-share:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create dist directory
        run: mkdir dist
      - name: Create archive
        run: tar -czf dist/repo-archive.tar.gz *