name: Archive Repository and Share on Slack

on:
  push:
    branches:
      - main

jobs:
  archive-and-share:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create archive
        run: tar -czf repo-archive.tar.gz .
      - name: Share on Slack
        uses: rtCamp/action-slack-notify@v3.5.0
        with:
          status: "success"
          message: "Archive download link: ${{ github.event.repository.html_url }}/archive/refs/heads/main.tar.gz"